/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {
  interface HTMLRaxxGoogleMapsElement extends HTMLStencilElement {
    'addMarker': (lat: number, lng: number) => void;
    'apikey': string;
    'getCenter': () => any;
  }
  var HTMLRaxxGoogleMapsElement: {
    prototype: HTMLRaxxGoogleMapsElement;
    new (): HTMLRaxxGoogleMapsElement;
  };
  interface HTMLElementTagNameMap {
    'raxx-google-maps': HTMLRaxxGoogleMapsElement;
  }
  interface ElementTagNameMap {
    'raxx-google-maps': HTMLRaxxGoogleMapsElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'raxx-google-maps': JSXElements.RaxxGoogleMapsAttributes;
    }
  }
  namespace JSXElements {
    export interface RaxxGoogleMapsAttributes extends HTMLAttributes {
      'apikey'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
